# Generated by Django 2.2.7 on 2020-05-31 22:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgPath', models.TextField(blank=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('difficulty', models.IntegerField(default=0)),
                ('url', models.TextField(blank=True, null=True)),
                ('steps', models.TextField(blank=True, null=True)),
                ('parts', models.TextField(blank=True, null=True)),
                ('partIDs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hub.ProjectCategories')),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hub.PartCategories')),
            ],
        ),
    ]
