# Generated by Django 2.2.7 on 2020-07-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='parts',
            field=models.TextField(null=True),
        ),
    ]
