# Generated by Django 2.2.7 on 2020-05-31 07:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='partsNeeded',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=50, null=True), null=True, size=None), null=True, size=None),
        ),
    ]
