# Generated by Django 2.2.7 on 2020-04-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
