# Generated by Django 2.2.9 on 2020-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='garage',
            field=models.ManyToManyField(blank=True, to='hub.Parts'),
        ),
    ]
