# Generated by Django 2.2.7 on 2020-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20200531_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='partsNeeded',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
