# Generated by Django 2.2.7 on 2020-06-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20200531_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='partsNeeded',
        ),
    ]
