# Generated by Django 2.2.7 on 2020-06-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_remove_project_partsneeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imgPath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='parts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='steps',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
