# Generated by Django 2.2.7 on 2020-06-05 20:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20200605_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePicturePath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='savedProjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, size=None),
        ),
    ]
