# Generated by Django 2.2.7 on 2020-05-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20200531_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='partsNeeded',
            new_name='parts',
        ),
    ]
