# Generated by Django 2.2.7 on 2020-06-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20200531_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('project', models.ManyToManyField(to='hub.Project')),
            ],
        ),
    ]
