# Generated by Django 2.2.7 on 2020-06-05 20:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20200605_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='savedProjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
    ]
