# Generated by Django 2.2.7 on 2020-06-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_auto_20200602_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.TextField(null=True, unique=True),
        ),
    ]
