# Generated by Django 2.2.7 on 2020-06-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_auto_20200605_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='upvotes',
        ),
    ]
