# Generated by Django 2.2.7 on 2020-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentParent',
            field=models.ManyToManyField(blank=True, to='hub.Comment'),
        ),
    ]
