# Generated by Django 2.2.7 on 2020-06-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_remove_project_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
    ]
