# Generated by Django 2.2.7 on 2020-06-04 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0010_auto_20200603_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
