# Generated by Django 2.2.7 on 2020-06-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_project_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
