# Generated by Django 2.2.7 on 2020-06-09 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_comment_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
