# Generated by Django 2.2.7 on 2020-06-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_upvote_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0)),
                ('support', models.FloatField(default=0)),
                ('lift', models.FloatField(default=0)),
                ('projects', models.ManyToManyField(blank=True, to='hub.Project')),
            ],
        ),
    ]
