# Generated by Django 2.2.7 on 2020-06-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_auto_20200608_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='parts',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
