# Generated by Django 2.2.7 on 2020-06-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_project_partnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.IntegerField(default=0),
        ),
    ]
