# Generated by Django 2.2.7 on 2020-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0016_project_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwd_reset_token',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passwd_reset_token_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
